"""Add summary to report

Revision ID: 00f4f29655d4
Revises: 88c93f8adfd0
Create Date: 2025-02-23 11:27:03.312573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00f4f29655d4'
down_revision: Union[str, None] = '88c93f8adfd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'summary')
    # ### end Alembic commands ###
