"""reload

Revision ID: 4020b8ba1cad
Revises: aaeb351233a1
Create Date: 2025-02-20 03:06:48.104702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4020b8ba1cad'
down_revision: Union[str, None] = 'aaeb351233a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cctv_data', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('cctv_info', sa.Column('api_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cctv_info', 'api_url')
    op.drop_column('cctv_data', 'image_url')
    # ### end Alembic commands ###
