"""get member's cctv in cctv_info table

Revision ID: 88c93f8adfd0
Revises: 4020b8ba1cad
Create Date: 2025-02-23 07:15:47.181401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c93f8adfd0'
down_revision: Union[str, None] = '4020b8ba1cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
