"""Add password to Member

Revision ID: 977c58ffc4cc
Revises: 627d59b6539f
Create Date: 2025-02-23 12:16:12.040909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '977c58ffc4cc'
down_revision: Union[str, None] = '627d59b6539f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'password')
    # ### end Alembic commands ###
