"""Add foreign key constraint for Report.cctv_id

Revision ID: ba6656c08701
Revises: 6cdfa6c67a61
Create Date: 2025-02-03 07:13:59.540565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba6656c08701'
down_revision: Union[str, None] = '6cdfa6c67a61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'report', 'cctv_info', ['cctv_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report', type_='foreignkey')
    # ### end Alembic commands ###
